version: "3.7"

services:
    mariadb:
        image: mariadb
        restart: always
        container_name: mariadb_friendup
        hostname: mariadb
        networks:
            - friendup-network
        environment:
            MYSQL_ROOT_PASSWORD: passw0rd2020
        ports: 
            - "3306:3306"
        volumes:
            - ./docker/mariadb:/docker-entrypoint-initdb.d/
            - ./db-data:/var/lib/mysql
    nginx:
        build:
            context: ./docker/nginx
            dockerfile: ./Dockerfile
        image: nginx
        hostname: nginx
        container_name: nginx_friendup
        ports:
            - 80:80
            - 443:443
        volumes: 
            - .:/var/www/html
            - ./docker/friendup/cfg/crt:/var/www/html/friendup/build/cfg/crt
            - ./docker/nginx/sites-available:/etc/nginx/sites-available
        networks: 
            - friendup-network
        depends_on: 
            - friendup
            - friendchat
    friendup:
        build:
            context: ./docker/friendup
            dockerfile: ./Dockerfile
        image: friendup
        restart: always
        container_name: friendup_core
        hostname: friendup
        extra_hosts:
            - "myfriendup.com:10.0.2.15"
            - "community.myfriendup.com:10.0.2.15"
            - "onlyoffice.myfriendup.com:10.0.2.15"
        networks:
            - friendup-network
        depends_on:
            - mariadb
        ports:
            - "6500:6500"
            - "6498:6498"
            - "6502:6502"
        volumes:
            # FriendOS and Friend configuration
            - ./friendup:/var/www/html/friendup
            - ./docker/friendup/cfg:/var/www/html/friendup/build/cfg
            # FriendOffice
            - ./friend-office:/var/www/html/friend-office
            # FriendChat app
            - ./docker/friendchat/friendchat/client:/var/www/html/friendup/build/resources/webclient/apps/FriendChat
    friendchat:
        build:
            context: ./docker/friendchat
            dockerfile: ./Dockerfile
        image: friendchat
        restart: always
        container_name: friendchat
        hostname: friendchat
        networks:
            - friendup-network
        depends_on: 
            - friendup
            - mariadb
        ports:
            - "3000:3000"
            - "3001:3001"
            - "27970:27970"
        volumes:
            - ./presence:/var/www/html/presence 
            - ./friendchat:/var/www/html/friendchat
    onlyoffice:
        image: onlyoffice/communityserver:11.0.0.1458
        networks:
            - friendup-network
        depends_on:
            - mariadb
            - documentserver
            - onlyoffice-mail-server
            - friendup
        ports:
            - "465:465"
            - "110:110"
            - "995:995"
            - "993:993"
        volumes:
            - ./onlyoffice_data:/var/www/onlyoffice/Data
            - ./docker/certs:/var/www/onlyoffice/Data/certs
            - ./document_data:/var/www/onlyoffice/DocumentServerData
            - /sys/fs/cgroup:/sys/fs/cgroup:ro
        restart: always
        container_name: onlyoffice
        hostname: onlyoffice
        environment:
            - ONLYOFFICE_CORE_MACHINEKEY=core_secret
            - DOCUMENT_SERVER_PORT_80_TCP_ADDR=documentserver
            - MYSQL_SERVER_ROOT_PASSWORD=passw0rd2020
            - MYSQL_SERVER_DB_NAME=onlyoffice 
            - MYSQL_SERVER_HOST=mariadb
            - MYSQL_SERVER_USER=onlyoffice_user
            - MYSQL_SERVER_PASS=onlyoffice_pass 
            - MAIL_SERVER_API_PORT=8081
            - MAIL_SERVER_API_HOST=onlyoffice-mail-server
            - MAIL_SERVER_DB_HOST=mariadb
            - MAIL_SERVER_DB_PORT=3306
            - MAIL_SERVER_DB_NAME=onlyoffice_mailserver
            - MAIL_SERVER_DB_USER=onlyoffice_mailserver_user
            - MAIL_SERVER_DB_PASS=onlyoffice_mailserver_user_pass
    documentserver:
        container_name: onlyoffice-document-server
        image: onlyoffice/documentserver:6.0.2
        extra_hosts:
            - "friend.serveit.co.nz:10.0.2.15"
            - "onlyoffice.serveit.co.nz:10.0.2.15"
        restart: always
        networks:
            - friendup-network
        expose:
            - '80'
            - '443'
        volumes:
            - ./document_data:/var/www/onlyoffice/Data
            - ./docker/certs:/var/www/onlyoffice/Data/certs
            - ./document_log:/var/log/onlyoffice
            - ./document_fonts:/usr/share/fonts/truetype/custom
            - ./document_forgotten:/var/lib/onlyoffice/documentserver/App_Data/cache/files/forgotten
            - ./friend-office/plugin/friend:/var/www/onlyoffice/documentserver/sdkjs-plugins/friend
            - ./docker/onlyoffice/default.json:/etc/onlyoffice/documentserver/default.json
    onlyoffice-mail-server:
        container_name: onlyoffice-mail-server
        image: onlyoffice/mailserver:latest
        depends_on:
            - mariadb
        hostname: smtp.thejuice.nz
        environment:
            - MYSQL_SERVER=mariadb
            - MYSQL_SERVER_PORT=3306
            - MYSQL_ROOT_USER=onlyoffice_mailserver_user
            - MYSQL_ROOT_PASSWD=onlyoffice_mailserver_user_pass
            - MYSQL_SERVER_DB_NAME=onlyoffice_mailserver
        networks:
            - friendup-network
        volumes:
            - ./mail/mail_data:/var/vmail
            - ./mail/mail_certs:/etc/pki/tls/mailserver
            - ./mail/mail_log:/var/log
        restart: always
        privileged: true
        ports: ['25:25','143:143','587:587']
        expose:
            - '8081'
    onlyoffice-control-panel:
        container_name: onlyoffice-control-panel
        depends_on:
            - documentserver
            - onlyoffice-mail-server
            - onlyoffice
        image: onlyoffice/controlpanel:2.9.0.351
        environment:
            - ONLYOFFICE_CORE_MACHINEKEY=core_secret
        expose:
            - '80'
            - '443'
        restart: always
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - ./controlpanel_data:/var/www/onlyoffice/Data
            - ./controlpanel_log:/var/log/onlyoffice
        networks:
            - friendup-network
    coturn:
        build:
            context: ./docker/coturn
            dockerfile: ./Dockerfile
        image: coturn
        restart: always
        container_name: coturn
        hostname: coturn
        networks:
            - friendup-network
        ports:
            - "4443:4443"
            - "8080:8080"
        volumes:
            - ./coturn:/var/www/html
            - ./docker/certs:/etc/certs
networks:
    friendup-network:
